fixup! tools/ocaml: Makefile to drive dune
Add a rule in the top-level  makefile that prepares everything for Dune.
Add a rule in Makefile.dune that looks for files that should've been
generated by the Makefile and if they are missing then print an error
message on what the user should run.
(this should be safe wrt to parallel make because if these files are
 missing then the build would've subsequently failed anyway)

Signed-off-by: Edwin Török <edvin.torok@citrix.com>

diff --git a/tools/ocaml/Makefile.dune b/tools/ocaml/Makefile.dune
--- a/tools/ocaml/Makefile.dune
+++ b/tools/ocaml/Makefile.dune
@@ -2,21 +2,11 @@ XEN_ROOT = $(CURDIR)/../..
 all: dune-all-check
 
 # Dune by default uses all available CPUs. Make doesn't.
-# Query the available CPUs an use all available for any of the make rules we call out to.
+# Query the available CPUs and use all available for any of the make rules we call out to.
 # -O is also needed with parallel make such that the build error and the build command causing
-#  the error are close together and not intersperesed with other output
+#  the error are close together and not interspersed with other output
 NPROC=$(shell getconf _NPROCESSORS_ONLN)
 MAKEN=$(MAKE) -j$(NPROC) -O
-
-# If the user hasn't run configure yet: do it now
-../config.status: ../configure
-	cd ../ && ./configure --with-xenstored=oxenstored
-
-# Files generated by the C Makefiles
-# These cannot be generated or called from dune, because XEN_ROOT would be wrong
-# (dune runs the build in _build/default subdir)
-../include/xen/xen.h: ../include/Makefile
-	$(MAKEN) -C ../include build V=
 
 # We want to link and use the Xen libraries built locally
 # without installing them system-wide
@@ -51,17 +41,23 @@ LIBRARY_PATH=$(subst $(eval) ,:,$(LIB_DIRS))
 # for location of various libs which moves between Xen versions
 include $(XEN_ROOT)/tools/Rules.mk
 
-XEN_DEPS=$(XEN_libxenctrl)/libxenctrl.so $(XEN_libxenevtchn)/libxenevtchn.so $(XEN_libxenguest)/libxenguest.so
+XEN_DEPS=$(XEN_libxenctrl)/libxenctrl.so
+XEN_DEPS+=$(XEN_libxenevtchn)/libxenevtchn.so
+XEN_DEPS+=$(XEN_libxenguest)/libxenguest.so
 
-$(XEN_DEPS):
-	$(MAKEN) -C ../libs V=
+# Cannot be generated from dune
+# Tell the user how to generate them
+../include/xen/xen.h ../config.status $(XEN_DEPS):
+	echo "Missing C headers or libraries" >&2
+	echo "Run make -C $(XEN_ROOT) build-tools-oxenstored-prepare -j$$(nproc)" >&2
+	exit 1
 
 # dune would refuse to run if there are build artifacts in the source directory
 # if we detect anything then run make clean to ensure these are removed
 # don't always call 'make clean' because it takes ~1.6s
 .PHONY: dune-pre
 dune-pre: ../config.status | ../include/xen/xen.h ../dune-workspace $(XEN_DEPS)
-	$(if $(wildcard libs/*/.ocamldep.make),$(MAKEN) clean,)
+	$(MAKEN) clean -s
 
 # Convenience targets
 dune-syntax-check: dune-pre
@@ -90,4 +86,3 @@ dune-install: dune-oxenstored
 
 dune-uninstall: dune-oxenstored
 	dune uninstall --destdir=$(DESTDIR) --prefix=$(prefix) --libdir=$(shell ocamlfind printconf destdir) --mandir=$(mandir) --etcdir=$(sysconfdir) --docdir=$(docdir)
-
